### ISSUE TITLE
Decimal values are not supported

### ISSUE THREAD

**Issue by shweta1122** [mahmoudZakaria90/vue-currency-directive#22]
If I try to enter amount like 444.44 it does not allow me to enter those

**Comment by mahmoudZakaria90** [comment]
Thank you for reporting it, gonna work on it.

**Comment by mahmoudZakaria90** [comment]
@shweta1122 Done, with [PR 24](https://github.com/mahmoudZakaria90/vue-currency-directive/pull/24/files) with adding support for `minimumFractionDigits` and `maximumFractionDigits`.
